# Generated by Django 2.2.10 on 2021-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='nome',
            new_name='nome_componente',
        ),
        migrations.RenameField(
            model_name='macroprocesso',
            old_name='nome',
            new_name='nome_macroprocesso',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='nome',
            new_name='nome_processo',
        ),
    ]
