# Generated by Django 2.2.10 on 2021-06-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210317_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='direcionador',
            field=models.ManyToManyField(related_name='processoDirecionador', to='main.Direcionador'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='entradaSaida',
            field=models.ManyToManyField(related_name='processoEntradaSaida', to='main.EntradaSaida'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='ferramenta',
            field=models.ManyToManyField(related_name='processoFerramenta', to='main.Ferramenta'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroProcesso_primario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroProcessoPrim', to='main.MacroProcesso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='macroProcessos_vinculados',
            field=models.ManyToManyField(blank=True, related_name='macroProcessoVinc', to='main.MacroProcesso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='parte',
            field=models.ManyToManyField(related_name='processoParte', to='main.Parte'),
        ),
    ]
