# Generated by Django 3.2.4 on 2021-06-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210616_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='macroProcessos_vinculados',
            field=models.ManyToManyField(blank=True, null=True, related_name='macroProcessoVinc', to='main.MacroProcesso'),
        ),
    ]
