version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-prod
    command: "gunicorn api_sgpo.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  static_volume:
  media_volume: