# Generated by Django 3.2.4 on 2022-02-27 04:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipoCliente', models.CharField(choices=[('Pessoa', 'Pessoa'), ('Unidade', 'Unidade')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_componente', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=200)),
                ('codigo', models.CharField(default='', max_length=5, unique=True)),
                ('tipo', models.CharField(choices=[('finalistico', 'finalistico'), ('direcionador', 'direcionador'), ('apoio', 'apoio')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direcionador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tipoParte', models.CharField(choices=[('L', 'Lei'), ('D', 'Decreto'), ('R', 'Resolução'), ('A', 'Ato'), ('Po', 'Portaria'), ('M', 'Manual')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(null=True, upload_to='arquivos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MacroProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_macroprocesso', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=200)),
                ('codigo', models.CharField(default='', max_length=5, unique=True)),
                ('componente_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.componente')),
                ('componentes_vinculados', models.ManyToManyField(blank=True, related_name='componentesVincAcess', to='main.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeParte', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20)),
                ('tipoParte', models.CharField(choices=[('Pe', 'Pessoa'), ('C', 'Cargo'), ('U', 'Unidade'), ('S', 'Setor'), ('O', 'Órgão'), ('C', 'Comitê'), ('Pa', 'Papel'), ('G', 'Grupo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipoSaida', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TiposUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTematico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tiposusuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tiposusuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_processo', models.CharField(max_length=200)),
                ('gestorPrincipal', models.CharField(max_length=200)),
                ('proprietario', models.CharField(max_length=200)),
                ('fronteiraDe', models.CharField(max_length=200)),
                ('fronteiraAte', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('statusProcesso', models.CharField(blank=True, choices=[('Em Aberto', 'Em Aberto'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('codigo', models.CharField(default='', max_length=5, unique=True)),
                ('proad', models.CharField(max_length=12)),
                ('versaop', models.IntegerField(default=0)),
                ('data_inicial_versao_processo', models.DateTimeField(auto_now=True)),
                ('etapas', models.TextField()),
                ('clientes', models.ManyToManyField(blank=True, related_name='cliente', to='main.Cliente')),
                ('direcionador', models.ManyToManyField(related_name='processoDirecionador', to='main.Direcionador')),
                ('entradas', models.ManyToManyField(related_name='processoEntradas', to='main.Entrada')),
                ('ferramenta', models.ManyToManyField(related_name='processoFerramenta', to='main.Ferramenta')),
                ('macroProcesso_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroProcessoPrim', to='main.macroprocesso')),
                ('macroProcessos_vinculados', models.ManyToManyField(blank=True, related_name='macroProcessoVinc', to='main.MacroProcesso')),
                ('parte', models.ManyToManyField(related_name='processoParte', to='main.Parte')),
                ('saidas', models.ManyToManyField(related_name='processoSaidas', to='main.Saida')),
            ],
        ),
    ]
