# Generated by Django 3.2.4 on 2021-11-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='clientes',
        ),
    ]
