# Generated by Django 3.2.4 on 2021-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='codigo',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
