# Generated by Django 3.2.4 on 2021-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_processo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='codigo',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='macroprocesso',
            name='codigo',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
