# Generated by Django 3.2.4 on 2021-11-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_processo_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcionador',
            old_name='Orgao',
            new_name='orgao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='entradaSaida',
        ),
    ]
