# Generated by Django 3.2.4 on 2021-12-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211205_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipoSaida', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], max_length=7)),
            ],
        ),
        migrations.RenameModel(
            old_name='EntradaSaida',
            new_name='Entrada',
        ),
        migrations.AddField(
            model_name='processo',
            name='entradas',
            field=models.ManyToManyField(related_name='processoEntradas', to='main.Entrada'),
        ),
        migrations.AddField(
            model_name='processo',
            name='saidas',
            field=models.ManyToManyField(related_name='processoSaidas', to='main.Saida'),
        ),
    ]
