# Generated by Django 3.2.4 on 2021-11-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211122_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcionador',
            old_name='ano',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='direcionador',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direcionador',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
