# Generated by Django 3.2.4 on 2022-02-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211212_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='arquivo',
            field=models.FileField(default='', upload_to='arquivos/%Y/%m/%d/'),
        ),
    ]
