# Generated by Django 3.2.4 on 2021-11-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211123_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='fronteirAte',
            new_name='fronteiraAte',
        ),
    ]
