# Generated by Django 3.2.4 on 2022-02-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_entrada_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos/%Y/%m/%d/'),
        ),
    ]
